namespace WinAPI
{
    using CookComputing.XmlRpc;
    using System;

    [XmlRpcMissingMapping(MappingAction.Ignore)]
    public class Proxy_VIF
    {
        public string[] allowed_operations;
        public object current_operations;
        public bool currently_attached;
        public string device;
        public string[] ipv4_allowed;
        public string[] ipv6_allowed;
        public string locking_mode;
        public string MAC;
        public bool MAC_autogenerated;
        public string metrics;
        public string MTU;
        public string network;
        public object other_config;
        public object qos_algorithm_params;
        public string qos_algorithm_type;
        public string[] qos_supported_algorithms;
        public object runtime_properties;
        public string status_code;
        public string status_detail;
        public string uuid;
        public string VM;
    }
}

